export enum Permissao {
  ADMIN = 'ROLE_ADMIN',
  RH = 'ROLE_RH',
  GERENTE_GERAL = 'ROLE_GERENTE_GERAL',
  GERENTE = 'ROLE_GERENTE',
  SUPERVISOR = 'ROLE_SUPERVISOR',
  VENDEDOR = 'ROLE_VENDEDOR',
  CONSULTOR_VENDAS = 'ROLE_CONSULTOR_VENDAS',
  FINANCEIRO = 'ROLE_FINANCEIRO',
  COBRADOR = 'ROLE_COBRADOR',
  ESTAGIARIO = 'ROLE_ESTAGIARIO',
}
