export enum Permissao {
    ADMINISTRADOR = 'ROLE_ADMINISTRADOR',
    RH = 'ROLE_RH',
    GERENTE_GERAL = 'ROLE_GERENTE_GERAL',
    GERENTE = 'ROLE_GERENTE',
    SUPERVISOR = 'ROLE_SUPERVISOR',
    VENDEDOR = 'ROLE_VENDEDOR',
    COLABORADOR = 'ROLE_COLABORADOR'
}