export enum Permissao {
  ADMIN = 'ROLE_ADMIN',
  RH = 'ROLE_RH',
  GERENTE_GERAL = 'ROLE_GERENTE_GERAL',
  GERENTE = 'ROLE_GERENTE',
  SUPERVISOR = 'ROLE_SUPERVISOR',
  VENDEDOR = 'ROLE_VENDEDOR',
  COLABORADOR = 'ROLE_COLABORADOR',
  CONSULTOR_VENDAS = 'CONSULTOR_VENDAS',
  FINANCEIRO = 'FINANCEIRO',
  COBRADOR = 'COBRADOR',
  ESTAGIARIO = 'ESTAGIARIO',
}
