export enum TipoRegistro {
  FALTA_AUSENCIA = 'FALTA_AUSENCIA',
  ATRASO = 'ATRASO',
  PROMOCAO = 'PROMOCAO',
  FALHA_ERRO = 'FALHA_ERRO',
  IDEIA_CONTRIBUICAO = 'IDEIA_CONTRIBUICAO',
  RECONTRATACAO = 'RECONTRATACAO',
  OUTROS = 'OUTROS',
  ADVERTENCIA = 'ADVERTENCIA',
  SUSPENSAO = 'SUSPENSAO',
  SUBPERFORMANCE = 'SUBPERFORMANCE',
  FOLGA = 'FOLGA',
}
