export enum Cargo {
  ADMIN = 'ADMIN',
  RH = 'RH',
  GERENTE_GERAL = 'GERENTE_GERAL',
  GERENTE = 'GERENTE',
  SUPERVISOR = 'SUPERVISOR',
  VENDEDOR = 'VENDEDOR',
  CONSULTOR_VENDAS = 'CONSULTOR_VENDAS',
  FINANCEIRO = 'FINANCEIRO',
  COBRADOR = 'COBRADOR',
  ESTAGIARIO = 'ESTAGIARIO',
}
