export enum TiposProcedimento {
  EXAME_ADMISSIONAL = 'EXAME_ADMISSIONAL',
  EXAME_DEMISSIONAL = 'EXAME_DEMISSIONAL',
  EXAME_PERIODICO = 'EXAME_PERIODICO',
  CONSULTA_MEDICA = 'CONSULTA_MEDICA',
  ACIDENTE_TRABALHO = 'ACIDENTE_TRABALHO',
  VACINA = 'VACINA',
  ATESTADO_MEDICO = 'ATESTADO_MEDICO',
  OUTROS = 'OUTROS',
}
