export enum TipoDemissao {
  SEM_JUSTA_CAUSA = 'SEM_JUSTA_CAUSA',
  POR_JUSTA_CAUSA = 'POR_JUSTA_CAUSA',
  QUEBRA_DE_CONTRATO_EMPREGADO = 'QUEBRA_DE_CONTRATO_EMPREGADO',
  QUEBRA_DE_CONTRATO_EMPREGADOR = 'QUEBRA_DE_CONTRATO_EMPREGADOR',
  PEDIDO_DE_DEMISSAO = 'PEDIDO_DE_DEMISSAO',
}
