import { Permissao } from 'src/app/login/permissao';
import { Endereco } from '../lojas/endereco';

export class Colaborador {
  id!: string;
  fotoUrl!: any;
  username!: string;
  dataNascimento!: string;
  estadoCivil!: string;
  genero!: string;
  etnia!: string;
  escolaridade!: string;
  curso!: string;
  nacionalidade!: string;
  naturalidade!: string;
  portadorDeficiencia!: string;
  deficiencia!: string;
  possuiFilhos!: string;
  quantidadeFilhos!: number;
  cpf!: string;
  rg!: string;
  orgaoExpedidor!: string;
  dataExpedicao!: string;
  nomeMae!: string;
  nomePai!: string;
  cnh!: string;
  reservista!: string;
  tituloDeEleitor!: string;
  zonaEleitoral!: string;
  secaoEleitoral!: string;
  pis!: string;
  ctpsNum!: string;
  ctpsSerie!: string;
  banco!: string;
  agencia!: string;
  contaCorrente!: string;
  documentos!: { documentoUrl: string; id: number; name: string }[];
  telefoneUm!: string;
  telefoneDois!: string;
  emailEmpresarial!: string;
  instagram!: string;
  endereco!: Endereco;
  loja!: string;
  dataAdmissao!: string;
  departamento!: string;
  cargo!: string;
  tipoDeContratacao!: string;
  salario!: string;
  periodoDeExperiencia!: string;
  dataDoContrato!: string;
  duracaoDoContrato!: number;
  dataTerminoDoContrato!: string;
  superiorResponsavel!: string;
  status!: string;
  emailPessoal!: string;
  password!: string;
  confirmPassword!: string;
}
